[package]
name = "devsim"
version = "0.1.0"
authors = ["Gregory Mitrano <gregory.mitrano@gmail.com>"]
edition = "2018"

[dependencies]
goblin = "0.2"
gumdrop = "0.8"
pbr = "1"

[dependencies.image]
default-features = false
features = ["png"]
version = "0.23"

[build-dependencies]
cmake = "0.1"
